### PR TITLE
Savefixes VIII

### LINKED ISSUE #2733: [GAME BUG]: Save issues in several games
### Checklist (we expect you to perform these steps before opening the issue)

- [x] I have searched for a similar issue in this repository and did not find one.
- [x] I am using an official build obtained from [releases](https://github.com/shadps4-emu/shadPS4/releases) or updated one of those builds using its in-app updater.
- [x] I have re-dumped the game and performed a clean install without mods and the issue is still present.
- [x] I have disabled all patches and cheats and the issue is still present.
- [x] I have all the required [system modules](https://github.com/shadps4-emu/shadps4-game-compatibility?tab=readme-ov-file#informations) installed.

### Describe the Bug

This occurs in the following titles:
- ~J-STARS Victory VS+ (CUSA01593)~ Fixed #2851 
- ~DRAGON BALL XENOVERSE (CUSA01341)~ Fixed #3099 
- ~DRAGON BALL XENOVERSE 2 (CUSA05350)~ Fixed #3099 

I'm creating this issue at the request of @viniciuslrangel
All tests were performed on the latest pre-release as-of the creation of this issue.

### Specify OS Version

Windows 11 23H2

### CPU

12th Gen Intel(R) Core(TM) i7-1280P

### GPU

Intel(R) Iris(R) Xe Graphics

### Amount of RAM in GB

32 GB

### Amount of VRAM in GB

16 GB

### PR DESCRIPTION
**Pull request by viniciuslrangel**
Fixes #2733 (I hope)

### CODE REVIEW

File: src/core/libraries/save_data/dialog/savedatadialog.cpp [hunk 1]
```diff
@@ -27,7 +27,7 @@ Error PS4_SYSV_ABI sceSaveDataDialogClose() {
         return Error::NOT_RUNNING;
     }
     g_save_dialog_ui.Finish(ButtonId::INVALID);
-    g_save_dialog_ui = SaveDialogUi{};
+    g_save_dialog_ui = std::move(SaveDialogUi{});
```
Comment (Osyotr) [inline src/core/libraries/save_data/dialog/savedatadialog.cpp]: `SaveDialogUi{}` is already an rvalue, no need to move.

File: src/core/libraries/save_data/dialog/savedatadialog.cpp [hunk 2]
```diff
@@ -84,7 +84,7 @@ Error PS4_SYSV_ABI sceSaveDataDialogOpen(const OrbisSaveDataDialogParam* param)
     g_result = {};
     g_state = SaveDialogState{*param};
     g_status = Status::RUNNING;
-    g_save_dialog_ui = SaveDialogUi(&g_state, &g_status, &g_result);
+    g_save_dialog_ui = std::move(SaveDialogUi(&g_state, &g_status, &g_result));
```
Comment (Osyotr) [inline src/core/libraries/save_data/dialog/savedatadialog.cpp]: Functions always return rvalues, no need to move.

**Comment by georgemoralis** [comment]
Report any regressions or fixes here pls

**Comment by StevenMiller123** [comment]
No improvement in the DRAGON BALL XENOVERSE titles. J-STARS Victory Vs+ is fixed though.

[DBXV save create.txt](https://github.com/user-attachments/files/19930630/DBXV.save.create.txt)
[DBXV save load failed.txt](https://github.com/user-attachments/files/19930631/DBXV.save.load.failed.txt)
[DBXV2 save create.txt](https://github.com/user-attachments/files/19930628/DBXV2.save.create.txt)
[DBXV2 save load failed.txt](https://github.com/user-attachments/files/19930629/DBXV2.save.load.failed.txt)

[J-STARS working.txt](https://github.com/user-attachments/files/19930680/J-STARS.working.txt)

**Comment by georgemoralis** [comment]
Time for savefixes IX

**Review by Osyotr — COMMENTED** [review]
Sadly, Catherine is not fixed.

File: src/core/libraries/save_data/dialog/savedatadialog.cpp (hunk 1 above)
Comment (viniciuslrangel) [reply src/core/libraries/save_data/dialog/savedatadialog.cpp]: Oh, thank. Left some test code

**Comment by GHU7924** [comment]
I don't know exactly if this is related, but game `Tearaway™ Unfolded` appears with this error when launched

Снимок экрана 2025-04-28 153500

if you don't press anything, then after about 12 seconds the emulator will close without errors, but the last spamming lines will be like this:

>[Core] <Error> stubs.cpp:42 CommonStub: Stub: sceCompanionHttpdGetEvent (nid: Vku4big+IYM) called, returning zero to 0x9002756ef
[Core] <Error> stubs.cpp:42 CommonStub: Stub: sceCompanionHttpdGetEvent (nid: Vku4big+IYM) called, returning zero to 0x9002756ef
[Core] <Error> stubs.cpp:42 CommonStub: Stub: sceCompanionHttpdGetEvent (nid: Vku4big+IYM) called, returning zero to 0x9002756ef

If someone can track down this error and tell **viniciuslrangel** what it is related to, that would be great.

**Comment by StevenMiller123** [comment]
@GHU7924 Could you share the full log?
Also make sure to set the log filter to "Lib.SaveData:Debug Lib.SaveDataDialog:Debug" when testing to make sure all the important save-related calls show up in the log.

**Comment by GHU7924** [comment]
[CUSA00562.zip](https://github.com/user-attachments/files/19941563/CUSA00562.zip)
Again, I'm not sure if this is related and maybe the error is happening for some other reason that affects the saves.

EDIT:

By the way, I don't really understand all this, but the filter content is not written to the log?

For example, right now:

>[Config] <Info> emulator.cpp:131 Run: General LogType: sync
[Config] <Info> emulator.cpp:132 Run: General isNeo: false
[Config] <Info> emulator.cpp:133 Run: GPU isNullGpu: false

It could be like this:

>[Config] <Info> emulator.cpp:131 Run: General LogType: sync
[Config] <Info> emulator.cpp:132 Run: Debug Log Filter: "*:Critical"
[Config] <Info> emulator.cpp:133 Run: General isNeo: false

It also turns out that the log was not changed, that LogType was moved to Debug:

>[Config] <Info> emulator.cpp:131 Run: General LogType: sync

and in theory it should be:

>[Config] <Info> emulator.cpp:131 Run: Debug LogType: sync
