### PR TITLE
libSceVideodec2: Update structs to match newer firmwares

### LINKED ISSUE #2604: [APP BUG]: ORBIS_VIDEODEC2_ERROR_STRUCT_SIZE does not give out a proper error
### Checklist

- [x] I have searched for a similar issue in this repository and did not find one.
- [x] I am using an official build obtained from [releases](https://github.com/shadps4-emu/shadPS4/releases) or updated one of those builds using its in-app updater.

### Describe the Bug

The error code ORBIS_VIDEODEC2_ERROR_STRUCT_SIZE is being triggered by Five Nights At Freddy's Security Breach (CUSA24172) in videodec2.cpp (sceVideodec2GetPictureInfo, currently at line 168) when trying to decode an mp4 video.

Emulator crashes with seemingly no errors

Image

[shad_log.txt](https://github.com/user-attachments/files/19101205/shad_log.txt)

### Reproduction Steps

Trigger that error code.

### Expected Behavior

Error should be shown in the log.

### Specify OS Version

Windows 10

### PR DESCRIPTION
**Pull request by StevenMiller123**
Based on some decompilation I did, some libSceVideodec2 structs were adjusted somewhere around firmware 6.50. Our previous code was built around older versions of the library, and as a result, newer versions of libSceAvPlayer.sprx and newer games that use libSceVideodec2 would hit the struct size error return.
This PR updates the structs, and updates the struct size checks to match how newer versions of libSceVideodec2 behave.

This should properly fix #2604, though the author of that issue probably can't test this. 

I've also thrown in a function export needed for Assassin's Creed Unity, since I don't see a point in making a separate one line PR for that.

### CODE REVIEW

File: src/core/libraries/videodec/videodec2.h [hunk 1]
```diff
@@ -73,8 +73,10 @@ struct OrbisVideodec2OutputInfo {
     u32 frameHeight;
     void* frameBuffer;
     u64 frameBufferSize;
+    u32 frameFormat;
+    u32 framePitchInBytes;
```
Comment (squidbus) [inline src/core/libraries/videodec/videodec2.h:77]: Shouldn’t we also populate these with something if they’re included in the struct?

Comment (StevenMiller123) [reply src/core/libraries/videodec/videodec2.h:77]: Should be fixed now, though after looking into this, I'm not sure we're setting `framePitch` properly.
I'll run some hardware tests to verify how this works once I get a chance.
